#!/usr/bin/env python3
"""根据 version.__version__ 生成 PyInstaller 用的 Windows 版本资源文件。

输出：仓库根目录 version_info.txt（供 build.spec 的 EXE(version=...) 使用）。
嵌入 FileVersion / ProductVersion 后，升级覆盖同路径 exe 时 Windows 更易刷新图标缓存。
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(Path(__file__).resolve().parent))
from version import __version__  # noqa: E402


def _quad(ver: str) -> tuple[int, int, int, int]:
    clean = re.sub(r"^v", "", ver).split("-")[0]
    parts = [int(x) for x in clean.split(".") if x.isdigit()]
    while len(parts) < 4:
        parts.append(0)
    return tuple(parts[:4])  # type: ignore[return-value]


def main() -> None:
    major, minor, patch, build = _quad(__version__)
    ver_str = f"{major}.{minor}.{patch}.{build}"
    # 080404B0 = 中文(中国) + Unicode
    content = f"""# UTF-8
# Auto-generated by scripts/gen_version_info.py — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({major}, {minor}, {patch}, {build}),
    prodvers=({major}, {minor}, {patch}, {build}),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          '080404B0',
          [
            StringStruct('CompanyName', 'qq353167950'),
            StringStruct('FileDescription', '公众号助手'),
            StringStruct('FileVersion', '{ver_str}'),
            StringStruct('InternalName', '公众号助手'),
            StringStruct('LegalCopyright', 'Copyright (C) qq353167950'),
            StringStruct('OriginalFilename', '公众号助手.exe'),
            StringStruct('ProductName', '公众号助手'),
            StringStruct('ProductVersion', '{ver_str}'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct('Translation', [0x0804, 1200])])
  ]
)
"""
    out = ROOT / "version_info.txt"
    out.write_text(content, encoding="utf-8")
    print(f"wrote {out} version={ver_str}")


if __name__ == "__main__":
    main()
